server:
  port: 8005

spring:
  application:
    name: VaultMS
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prime_vault
    username: root
    password: Sajeed@07
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format.sql: true
  cloud:
    consul:
      discovery:
        hostname: localhost

gatewayUri: http://localhost:8000
