server:
  port: 8000

spring:
  application:
    name: GatewayMS
  cloud:
    consul:
      discovery:
        hostname: localhost
    gateway:
      globalCors:
        cors-configurations:
          '[/**]': # Define a unique key for your CORS configuration
            allowedOriginPatterns: "*" # Allow requests from all origins
            allowedMethods: "*" # Allow all HTTP methods
            allowedHeaders: "*" # Allow all request headers
            allowCredentials: true
      routes:
        - id: UserMS
          uri: lb://UserMS
          predicates:
            - Path=/auth/**
        - id: UserMS
          uri: lb://UserMS
          predicates:
            - Path=/profile/**
          filters:
            - JwtAuthenticationFilter
        - id: MovieMS
          uri: lb://MovieMS
          predicates:
            - Path=/movie/**
          filters:
            - JwtAuthenticationFilter
        - id: CartMS
          uri: lb://CartMS
          predicates:
            - Path=/cart/**
          filters:
            - JwtAuthenticationFilter
        - id: OrderMS
          uri: lb://OrderMS
          predicates:
            - Path=/order/**
          filters:
            - JwtAuthenticationFilter
        - id: VaultMS
          uri: lb://VaultMS
          predicates:
            - Path=/vault/**
          filters:
            - JwtAuthenticationFilter




