server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: CustomerMS
          uri: http://localhost:8001
          predicates:
            - Path=/auth/**
        - id: MovieMS
          uri: http://localhost:8002
          predicates:
            - Path=/movie/**
#          filters:
#            - JwtAuthenticationFilter



