server:
  port: 8004

spring:
  application:
    name: OrderMS
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format.sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prime_order
    username: root
    password: Sajeed@07
  cloud:
    consul:
      discovery:
        hostname: localhost