server:
  port: 8001
spring:
  application:
    name: UserMS
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prime_user
    username: root
    password: Sajeed@07
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format.sql: true
  cloud:
    consul:
      discovery:
        hostname: localhost

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: mdsajeedmds@gmail.com
spring.mail.password: xmuclvbnlmuossqe
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
