server:
  port: 8001
spring:
  application:
    name: UserMS
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prime_user
    username: root
    password: Sajeed@07
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format.sql: true
  cloud:
    consul:
      discovery:
        hostname: localhost
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: mdsajeedmds@gmail.com
    password: ${SMTP_PASSWORD}
    port: 587

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

application:
  bucket:
    name: primeclone





