server:
  port: 8003

spring:
  application:
    name: CartMS
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prime_cart
    username: root
    password: Sajeed@07
